### ISSUE TITLE
write javadoc specs for comments controller

### ISSUE THREAD

**Issue by th3bossc** [th3bossc/NITCONF-SE_LAB#18]

**Comment by Xolinnax** [comment]
Issue has been resolved in the following commit:
https://github.com/th3bossc/NITCONF-SE_LAB/commit/b495440a979fb03e9aa83cb704a3111b0842d30b

**Comment by Xolinnax** [comment]
Issue has been resolved in the following commit:
https://github.com/th3bossc/NITCONF-SE_LAB/commit/b495440a979fb03e9aa83cb704a3111b0842d30b
